name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Version compatible avec ton projet back-end

      - name: Install Dependencies
        working-directory: ./Backend
        run: npm install

      - name: Run Backend Tests
        working-directory: ./Backend
        run: npm test

      - name: Start Backend Server (Optional)
        working-directory: ./Backend
        run: npm start
